[hdfs] Fix DNS resolution for headless services
DNS entries are not registered fast enough in headless services.
This depends on cloud vendor (in GKE it's up to 60s).
Without it pods are up and running only on first start, but after
restart java apps will fail with error messages such as:

  hdfs-namenode-0 namenode java.lang.IllegalArgumentException:
  java.net.UnknownHostException: hdfs-namenode

Set in headless services spec.publishNotReadyAddresses: true,
which will enforce registration of DNS hosts even if they are not ready.
Ready state is based on pod readiness/liveness probes, if they pass,
the given pod is added to the endpoints.

In this setup enforcing publishing DNS entries, which are not ready
is not an issue. Actually this is expected because the way
Hadoop stack was designed. So the DNS entries should be added,
while appropriate java apps will handle the actual availability of the
processes within pods.

Tested for over 5 days on GKE preemptible instances.